### ISSUE TITLE
Align the boxes in the main page so that every body gets the same place

### ISSUE THREAD

**Issue by lorismichel** [lorismichel/forty-jekyll-theme#1]
Melvin and Benedikt, can you please work on this issue? This is a good start for @BenediktRamsauer  to introduce Melvin to the workflow  
issue raised ---> creation of a branch ---> code to solve the problem + commit of during process --> final commit with key word solved issue #of issue in the commit --> somebody merge the branch into the online branch gh-pages (remark this is the only online branch)

please look at the following reference:
https://gist.github.com/digitaljhelms/4287848

**Comment by BenediktRamsauer** [comment]
I'm on it. 
I'll first try to understand how Jekyll (https://jekyllrb.com/) works.

**Comment by BenediktRamsauer** [comment]
I think that I narrowed down where the size of the boxes is decided. It is in the java script you can find in the file **'assets/js/ie/backgroundsize.min.htc'**. 

This claim is based on the following "discoveries".
[1] The home page contains all the elements we see when looking at our "Notre équipe" page.
[2] More specifically, posts are added up in the the file '_includes/titles.html' (in ).
[3] In this latter file, we can see that 'posts' (and 'pages') are actually <article> structures.
[4] Such definition of structure can be found in the file '_sass/ie8.scss' in the /* Titles */ section.
[5] In this section, we can read the following line: 
-ms-behavior: url('assets/js/ie/backgroundsize.min.htc');
which leads me to think that the size of the background (or image?) is defined by this script.

**Comment by BenediktRamsauer** [comment]
I have re-indented all the javascript part of the file to have a better understanding of its meaning. Ask me if you need it!
